# Generated by Django 2.0.1 on 2018-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=128, null=True)),
                ('image', models.ImageField(max_length=256, upload_to='media/')),
                ('score', models.FloatField(default=0.0, null=True, verbose_name='score of the classification')),
            ],
        ),
    ]
